// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  define(function() {
    var activate, add, deactivate, debug, features, get, isActive, reset, showLog, state, subscribe, subscribers, _buildFeature, _buildSubscriber, _log, _notifySubscriberOnActivate, _notifySubscribersOnActivate, _notifySubscribersOnDeactivate;
    features = {};
    subscribers = {};
    showLog = false;
    _log = function(message, args, prefix) {
      if (args == null) {
        args = {};
      }
      if (prefix == null) {
        prefix = '[pinball.js]';
      }
      if (showLog) {
        return console.log("" + prefix + " " + message, args);
      }
    };
    _notifySubscribersOnActivate = function(name) {
      var subscriber, _i, _len, _ref, _results;
      if (subscribers[name] == null) {
        subscribers[name] = [];
      }
      _ref = subscribers[name];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        subscriber = _ref[_i];
        _results.push(_notifySubscriberOnActivate(subscriber));
      }
      return _results;
    };
    _notifySubscriberOnActivate = function(subscriber) {
      return subscriber.onActivate();
    };
    _notifySubscribersOnDeactivate = function(name) {
      var subscriber, _i, _len, _ref, _results;
      if (subscribers[name] == null) {
        subscribers[name] = [];
      }
      _ref = subscribers[name];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        subscriber = _ref[_i];
        _results.push(subscriber.onDeactivate());
      }
      return _results;
    };
    add = function(list) {
      var feature, name, _results;
      _results = [];
      for (name in list) {
        feature = list[name];
        features[name] = _buildFeature(feature.available, feature.activeByDefault);
        _log("Added feature " + name + ". %O", feature);
        if (feature.activeByDefault) {
          _results.push(activate(name));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    get = function(name) {
      return features[name];
    };
    _buildFeature = function(available, activeByDefault) {
      return {
        available: available != null ? available : true,
        active: false,
        activeByDefault: activeByDefault != null ? activeByDefault : false
      };
    };
    activate = function(name) {
      var feature;
      feature = get(name);
      if ((feature != null) === false) {
        return _log("Attempted to activate " + name + ", but it was not found.");
      } else if (feature != null ? feature.available : void 0) {
        if (feature.active) {
          return _log("Attempted to activate " + name + ", but it is already active. %O", feature);
        } else {
          _log("Activate feature " + name + ". %O", feature);
          feature.active = true;
          return _notifySubscribersOnActivate(name);
        }
      } else {
        return _log("Attempted to activate " + name + ", but it is not available. %O", feature);
      }
    };
    deactivate = function(name) {
      var feature;
      feature = get(name);
      if ((feature != null) === false) {
        return _log("Attempted to deactivate " + name + ", but it was not found.");
      } else if (feature != null ? feature.active : void 0) {
        _log("Dectivate feature " + name + ". %O", feature);
        feature.active = false;
        return _notifySubscribersOnDeactivate(name);
      } else {
        return _log("Attempted to deactivate " + name + ", but it was already inactive. %O", feature);
      }
    };
    isActive = function(name) {
      var _ref;
      return (_ref = get(name)) != null ? _ref.active : void 0;
    };
    _buildSubscriber = function(onActivate, onDeactivate) {
      return {
        onActivate: onActivate != null ? onActivate : function() {},
        onDeactivate: onDeactivate != null ? onDeactivate : function() {}
      };
    };
    subscribe = function(name, onActivate, onDeactivate) {
      var subscriber;
      subscriber = _buildSubscriber(onActivate, onDeactivate);
      if (subscribers[name] == null) {
        subscribers[name] = [];
      }
      subscribers[name].push(subscriber);
      if (isActive(name)) {
        return _notifySubscriberOnActivate(subscriber);
      }
    };
    state = function() {
      return features;
    };
    reset = function() {
      return features = {};
    };
    debug = function() {
      return showLog = true;
    };
    return {
      add: add,
      get: get,
      activate: activate,
      deactivate: deactivate,
      isActive: isActive,
      subscribe: subscribe,
      state: state,
      reset: reset,
      debug: debug
    };
  });

}).call(this);
