// Generated by CoffeeScript 1.7.1
(function() {
  'use strict';
  define(function() {
    var activate, add, buildFeature, features, get, reset, state;
    features = {};
    add = function(list) {
      var attributes, name, _results;
      _results = [];
      for (name in list) {
        attributes = list[name];
        _results.push(features[name] = buildFeature(attributes.available, attributes.activatedByDefault));
      }
      return _results;
    };
    get = function(name) {
      return features[name];
    };
    buildFeature = function(available, activatedByDefault) {
      return {
        available: available,
        activated: false,
        activatedByDefault: activatedByDefault
      };
    };
    activate = function(name) {
      var feature;
      feature = get(name);
      if (feature != null ? feature.available : void 0) {
        return feature.activated = true;
      }
    };
    state = function() {
      return features;
    };
    reset = function() {
      return features = {};
    };
    return {
      add: add,
      get: get,
      activate: activate,
      state: state,
      reset: reset
    };
  });

}).call(this);
